### ISSUE TITLE
Training on Covid19 dataset

### ISSUE THREAD

**Issue by huyhoang240101** [VinAIResearch/PhoNLP#8]
Hi, I'm having a problem trying to train the model on the Vietnamese Covid 19 NER dataset. This dataset is in the .conll form and I have the error from the compilers sad like below. I can't figure this error out, I wonder if the reason for this is because of the .conll format (the sample data format is .txt) or I need to do some preprocessed for the Covid 19 dataset. Can you suggest a solution for this. 
Traceback (most recent call last):
  File "run_phonlp.py", line 526, in <module>
    main()
  File "run_phonlp.py", line 128, in main
    train(args)
  File "run_phonlp.py", line 146, in train
    vocab = BuildVocab(args, args["train_file_pos"], train_doc_dep, args["train_file_ner"]).vocab
  File "/content/PhoNLP/phonlp/models/jointmodel/data.py", line 440, in __init__
    self.vocab = self.build_vocab(data_dep, data_pos, data_ner)
  File "/content/PhoNLP/phonlp/models/jointmodel/data.py", line 446, in build_vocab
    ner_tag = TagVocab(data_ner, idx=1)
  File "/content/PhoNLP/phonlp/models/common/vocab.py", line 27, in __init__
    self.build_vocab()
  File "/content/PhoNLP/phonlp/models/ner/vocab.py", line 11, in build_vocab
    counter = Counter([w[self.idx] for sent in self.data for w in sent])
  File "/content/PhoNLP/phonlp/models/ner/vocab.py", line 11, in <listcomp>
    counter = Counter([w[self.idx] for sent in self.data for w in sent])
IndexError: list index out of range

**Comment by thelinhbkhn2014** [comment]
Because PhoNLP is a multi-task learning model, you need enough data for 3 tasks ( NER, POS tagging, and Dependency parsing) to train PhoNLP.
